### ISSUE TITLE
Create overload for single message

### ISSUE THREAD

**Issue by npnelson** [MedOneSystems/BoltConnectWebApi#1]
The only overload allows for sending messages as a list. We plan to send one at a time. The current code requires me to allocate a list with a single item.

It's not a big deal, but AFAIK I have to unnecessarily allocate a list.

**Comment by sillyotter** [comment]
The API and interface code was written like that on purpose.  The proxy we provided that you chose not to use buffers up inbound messages and sends them in batches. This reduces the overhead associated with the creation of new connections to our servers, reduces the amount of space wasted sending customer ids, reduces the number of API endpoint calls we have to handle, and may, depending on how things are done, allow the HTTP compression algorithms to have something to work with.   

Since the proxy was designed to deal with network failures, and knew that it may have to store and send messages collected over some duration, it will in those cases always have a buffer of messages to send.  If it has to save locally a pack of messages when network is down, it can also do that all the time, and send out messages every N seconds - when possible and needed - with no down sides and the benefits of batched sending mentioned above.  A delay of a few seconds to minutes in receiving the messages will not be a problem.

The API, which is meant to support the proxy server, must therefor be built to accept a list of messages in one transaction.  The interface code, therefor, will also need to provide an interface to accept a list of messages at one time.  But, knowing that your use case is a possibility, a batch interface also allows you to send a list with a single element in it, should you find that necessary.  The single method will provide for both use cases.  Providing a new API endpoint that accepts a new message format with a single message is not needed, nor efficient, and providing a class library function that creates a list for you from a single message doesn't prevent you from having to allocate a list.  It just moves the allocation around, so its no more efficient than anything else. 

It at best prevents you from typing 7 characters - `new[]{}`.

**Comment by npnelson** [comment]
I am going to close this, but I will say that we will be sending you one message at a time. We will not be buffering messages locally because we do not want to be in the unenviable position of having acked messages before they are hardened to the cloud and then having a hardware failure at the receiver resulting in the loss of any buffered messages. We wouldn't even know what needed to be resent.
